make migrate:
		python3 manage.py migrate

make migrations:
		python3 manage.py makemigrations

make user:
		python3 manage.py createsuperuser

make serve:
		python3 manage.py runserver

make shell:
		python3 manage.py shell